apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/docker-gke-project-sainadha/gcp-devops-repo/gcp-devops-app:v1
        ports:
        - containerPort: 8080
